# this file configures ruff, if the fabric-testing project gets a pyproject.toml,
# then the following configuration can be moved to that file

line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint]
select = [
    "E", #pycodestyle
    "F", # Pyflakes
    "I", # isort
    "BLE"
]

ignore = ["E402"]
# see rule list here: https://docs.astral.sh/ruff/rules/
