name: PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint_and_format:
    uses: ./.github/workflows/lint-and-format.yml

  unit_tests_ubuntu:
    needs: lint_and_format
    uses: ./.github/workflows/unittest.yml
    with:
      os: ubuntu-latest  # Pass the OS as an input

  unit_tests_windows:
    needs: lint_and_format
    uses: ./.github/workflows/unittest.yml
    with:
      os: windows-latest  # Pass the OS as an input
